import type { Distributor, Client, Order, Promotion, RankingEntry, Invoice, Product, Role, AdminUser, Visit, Reward, Redemption, Discount, LoyaltyProgram, PointsHistoryEntry, AdminRedemption } from "./types"

export const mockConsultant = {
  id: "cons-1",
  firstName: "Anna",
  lastName: "Kowalska",
  phone: "+48 600 123 456",
  email: "anna.kowalska@soymax.pl",
}

export const mockDistributor: Distributor = {
  id: "dist-1",
  companyName: "AgroPartner Sp. z o.o.",
  nip: "1234567890",
  address: "ul. Polna 15, 00-001 Warszawa",
  phone: "+48 501 234 567",
  email: "kontakt@agropartner.pl",
  distributorCode: "DIST-2024-0042",
  baseDiscount: 5,
  programDiscount: 2,
  consultant: mockConsultant,
  registeredClientsCount: 18,
  activeClientsCount: 15,
  ownerFirstName: "Krzysztof",
  ownerLastName: "Malinowski",
  createdAt: "2024-03-15",
  points: 250,
  isActive: true,
  salespersonId: "admin-2",
}

export const mockClients: Client[] = [
  {
    id: "client-1",
    firstName: "Jan",
    lastName: "Nowak",
    phone: "+48 600 111 222",
    email: "jan.nowak@gmail.com",
    status: "active",
    points: 1250,
    registrationDate: "2024-01-15",
    lastPurchaseDate: "2024-12-10",
    distributorId: "dist-1",
    newsletter: true,
  },
  {
    id: "client-2",
    firstName: "Maria",
    lastName: "Wiśniewska",
    phone: "+48 600 333 444",
    email: "maria.w@gmail.com",
    status: "active",
    points: 890,
    registrationDate: "2024-02-20",
    lastPurchaseDate: "2024-12-05",
    distributorId: "dist-1",
    newsletter: false,
  },
  {
    id: "client-3",
    firstName: "Piotr",
    lastName: "Kowalczyk",
    phone: "+48 600 555 666",
    email: "piotr.k@wp.pl",
    status: "inactive",
    points: 320,
    registrationDate: "2024-03-10",
    lastPurchaseDate: "2024-08-15",
    distributorId: "dist-1",
    newsletter: true,
  },
  {
    id: "client-4",
    firstName: "Agnieszka",
    lastName: "Zielińska",
    phone: "+48 600 777 888",
    email: "a.zielinska@onet.pl",
    status: "active",
    points: 2100,
    registrationDate: "2024-01-05",
    lastPurchaseDate: "2024-12-12",
    distributorId: "dist-1",
    newsletter: true,
  },
  {
    id: "client-5",
    firstName: "Tomasz",
    lastName: "Lewandowski",
    phone: "+48 600 999 000",
    email: "t.lewandowski@gmail.com",
    status: "active",
    points: 560,
    registrationDate: "2024-04-18",
    lastPurchaseDate: "2024-11-28",
    distributorId: "dist-1",
    newsletter: false,
  },
]

export const mockOrders: Order[] = [
  {
    id: "order-1",
    orderNumber: "ZAM/2024/12/001",
    date: "2024-12-10",
    netValue: 4500,
    grossValue: 5535,
    status: "completed",
    appliedDiscount: 7,
    distributorId: "dist-1",
    items: [
      { id: "item-1", productName: "Soymax Premium 25kg", quantity: 10, unitPrice: 250, totalPrice: 2500 },
      { id: "item-2", productName: "Soymax Standard 25kg", quantity: 10, unitPrice: 200, totalPrice: 2000 },
    ],
  },
  {
    id: "order-2",
    orderNumber: "ZAM/2024/12/002",
    date: "2024-12-08",
    netValue: 2800,
    grossValue: 3444,
    status: "in_progress",
    appliedDiscount: 7,
    distributorId: "dist-1",
    items: [{ id: "item-3", productName: "Soymax Bio 20kg", quantity: 8, unitPrice: 350, totalPrice: 2800 }],
  },
  {
    id: "order-3",
    orderNumber: "ZAM/2024/11/045",
    date: "2024-11-25",
    netValue: 6200,
    grossValue: 7626,
    status: "completed",
    appliedDiscount: 7,
    distributorId: "dist-1",
    items: [
      { id: "item-4", productName: "Soymax Premium 25kg", quantity: 15, unitPrice: 250, totalPrice: 3750 },
      { id: "item-5", productName: "Soymax Starter 10kg", quantity: 14, unitPrice: 175, totalPrice: 2450 },
    ],
  },
]

export const mockPromotions: Promotion[] = [
  {
    id: "promo-1",
    title: "Podwójne punkty!",
    description: "X2 punkty za wszystkie produkty z linii Soymax Premium do końca grudnia",
    fullDescription: `Weź udział w naszej wyjątkowej promocji i zbieraj **podwójne punkty** za każdy zakup produktów z linii Soymax Premium!

**Jak to działa?**
- Każdy zakup produktu Soymax Premium = 2x więcej punktów
- Punkty naliczane automatycznie przy zamówieniu
- Brak limitu punktów do zdobycia

**Produkty objęte promocją:**
- Soymax Premium 25kg
- Soymax Premium Plus 25kg
- Soymax Premium Bio 20kg

**Okres trwania:** 1-31 grudnia 2024

Im więcej zamawiasz, tym więcej zyskujesz! Punkty możesz wymienić na atrakcyjne nagrody w katalogu nagród.`,
    imageUrl: "/double-points-promotion-green-agriculture-soybeans.jpg",
    startDate: "2024-12-01",
    endDate: "2024-12-31",
    type: "points",
    multiplier: 2,
    assignedProductIds: ["prod-1", "prod-5"],
    isActive: true,
  },
  {
    id: "promo-2",
    title: "Nowy produkt: Soymax Bio+",
    description: "Poznaj naszą najnowszą mieszankę paszową z certyfikatem ekologicznym",
    fullDescription: `Przedstawiamy **Soymax Bio+** - naszą najnowszą, w pełni ekologiczną mieszankę paszową stworzoną z myślą o zrównoważonym rolnictwie.

**Kluczowe cechy:**
- 100% składników z certyfikowanych upraw ekologicznych
- Wysoka zawartość białka (min. 44%)
- Bez GMO, bez antybiotyków
- Certyfikat EU Organic

**Dla kogo?**
Idealna dla gospodarstw prowadzących produkcję ekologiczną lub planujących przejście na metody bio.

**Promocja wprowadzająca:**
Zamów Soymax Bio+ do końca stycznia i otrzymaj **+50 punktów bonus** do każdego zamówienia!`,
    imageUrl: "/organic-bio-feed-product-green-soybeans-eco.jpg",
    startDate: "2024-12-01",
    endDate: "2025-01-31",
    type: "product",
    assignedProductIds: ["prod-3", "prod-6"],
    isActive: true,
  },
  {
    id: "promo-3",
    title: "Zimowa promocja",
    description: "15% rabatu na zamówienia powyżej 10 000 zł netto",
    fullDescription: `Skorzystaj z naszej **zimowej promocji** i zaoszczędź na większych zamówieniach!

**Zasady promocji:**
- Zamówienia o wartości **10 000 - 19 999 zł netto**: +1% do rabatu
- Zamówienia o wartości **20 000 - 49 999 zł netto**: +2% do rabatu  
- Zamówienia o wartości **50 000+ zł netto**: +3% do rabatu

**Ważne informacje:**
- Rabat naliczany automatycznie przy składaniu zamówienia
- Łączy się z Twoim podstawowym rabatem i rabatem z programu lojalnościowego
- Dotyczy wszystkich produktów z oferty SOYMAX

**Okres trwania:** 15 grudnia 2024 - 28 lutego 2025

Zaplanuj zakupy na zimę i zyskaj dodatkowe oszczędności!`,
    imageUrl: "/winter-sale-discount-snow-agriculture-barn.jpg",
    startDate: "2024-12-15",
    endDate: "2025-02-28",
    type: "info",
    discountBonus: 3,
    assignedProductIds: [],
    isActive: true,
  },
  {
    id: "promo-4",
    title: "Starter dla młodych",
    description: "-10% na produkty linii Starter dla nowych klientów",
    fullDescription: "Promocja wprowadzająca dla nowych klientów na całą linię produktów Starter.",
    imageUrl: "/starter-young-animals-feed.jpg",
    startDate: "2024-11-01",
    endDate: "2025-03-31",
    type: "product",
    discountBonus: 10,
    assignedProductIds: ["prod-4"],
    isActive: true,
  },
  {
    id: "promo-5",
    title: "Black Week - Standard",
    description: "Promocja na produkty Standard zakończona",
    fullDescription: "Promocja Black Week na produkty Standard.",
    imageUrl: "/standard-soy-feed-bag.jpg",
    startDate: "2024-11-25",
    endDate: "2024-12-01",
    type: "product",
    discountBonus: 20,
    assignedProductIds: ["prod-2"],
    isActive: false,
  },
]

export const mockRanking: RankingEntry[] = [
  {
    position: 1,
    distributorId: "dist-top1",
    companyName: "Agro-Lider Sp. z o.o.",
    clientsCount: 87,
    isCurrentUser: false,
  },
  { position: 2, distributorId: "dist-top2", companyName: "FarmPartner", clientsCount: 72, isCurrentUser: false },
  { position: 3, distributorId: "dist-top3", companyName: "ZielonePole", clientsCount: 65, isCurrentUser: false },
  { position: 4, distributorId: "dist-top4", companyName: "AgroBiznes24", clientsCount: 54, isCurrentUser: false },
  { position: 5, distributorId: "dist-top5", companyName: "PolskaFarma", clientsCount: 48, isCurrentUser: false },
  {
    position: 12,
    distributorId: "dist-1",
    companyName: "AgroPartner Sp. z o.o.",
    clientsCount: 18,
    isCurrentUser: true,
  },
]

export const mockInvoices: Invoice[] = [
  {
    id: "inv-1",
    invoiceNumber: "FV/2024/12/0042",
    date: "2024-12-10",
    dueDate: "2024-12-24",
    netValue: 4500,
    grossValue: 5535,
    status: "pending",
    pdfUrl: "/invoices/FV-2024-12-0042.pdf",
    distributorId: "dist-1",
  },
  {
    id: "inv-2",
    invoiceNumber: "FV/2024/12/0038",
    date: "2024-12-05",
    dueDate: "2024-12-19",
    netValue: 2800,
    grossValue: 3444,
    status: "paid",
    pdfUrl: "/invoices/FV-2024-12-0038.pdf",
    distributorId: "dist-1",
  },
  {
    id: "inv-3",
    invoiceNumber: "FV/2024/11/0125",
    date: "2024-11-25",
    dueDate: "2024-12-09",
    netValue: 6200,
    grossValue: 7626,
    status: "paid",
    pdfUrl: "/invoices/FV-2024-11-0125.pdf",
    distributorId: "dist-1",
  },
  {
    id: "inv-4",
    invoiceNumber: "FV/2024/11/0098",
    date: "2024-11-15",
    dueDate: "2024-11-29",
    netValue: 3150,
    grossValue: 3874.5,
    status: "paid",
    pdfUrl: "/invoices/FV-2024-11-0098.pdf",
    distributorId: "dist-1",
  },
  {
    id: "inv-5",
    invoiceNumber: "FV/2024/11/0076",
    date: "2024-11-08",
    dueDate: "2024-11-22",
    netValue: 8900,
    grossValue: 10947,
    status: "paid",
    pdfUrl: "/invoices/FV-2024-11-0076.pdf",
    distributorId: "dist-1",
  },
  {
    id: "inv-6",
    invoiceNumber: "FV/2024/10/0210",
    date: "2024-10-28",
    dueDate: "2024-11-11",
    netValue: 5400,
    grossValue: 6642,
    status: "paid",
    pdfUrl: "/invoices/FV-2024-10-0210.pdf",
    distributorId: "dist-1",
  },
]

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    name: "Soymax Premium 25kg",
    category: "premium",
    description: "Najwyższej jakości pasza sojowa dla bydła mlecznego i opasowego",
    protein: 46,
    weight: 25,
    unit: "kg",
    pricePerUnit: 250,
    imageUrl: "/premium-soy-feed-bag.jpg",
    inStock: true,
    features: ["Wysoka strawność", "Optymalna zawartość białka 46%", "Bez GMO", "Dla bydła mlecznego i opasowego"],
    tags: ["bydlo-mleczne", "bydlo-opasowe", "premium"],
  },
  {
    id: "prod-2",
    name: "Soymax Standard 25kg",
    category: "standard",
    description: "Uniwersalna pasza dla bydła mlecznego i opasowego",
    protein: 44,
    weight: 25,
    unit: "kg",
    pricePerUnit: 200,
    imageUrl: "/standard-soy-feed-bag.jpg",
    inStock: true,
    features: ["Dobra strawność", "Zawartość białka 44%", "Uniwersalne zastosowanie", "Optymalna cena"],
    tags: ["uniwersalny", "standard"],
  },
  {
    id: "prod-3",
    name: "Soymax Bio+ 20kg",
    category: "bio",
    description: "Ekologiczna pasza sojowa z certyfikatem EU Organic",
    protein: 45,
    weight: 20,
    unit: "kg",
    pricePerUnit: 350,
    imageUrl: "/organic-bio-soy-feed-bag.jpg",
    inStock: true,
    features: [
      "100% składników ekologicznych",
      "Certyfikat EU Organic",
      "Bez GMO i antybiotyków",
      "Zawartość białka 45%",
    ],
    tags: ["bio", "ekologiczny", "certyfikat-eu"],
  },
  {
    id: "prod-4",
    name: "Soymax Starter 10kg",
    category: "starter",
    description: "Specjalistyczna pasza dla młodych zwierząt",
    protein: 48,
    weight: 10,
    unit: "kg",
    pricePerUnit: 175,
    imageUrl: "/starter-young-animals-feed.jpg",
    inStock: true,
    features: [
      "Dla cieląt i młodych zwierząt",
      "Najwyższa zawartość białka 48%",
      "Łatwo przyswajalna",
      "Wspiera rozwój",
    ],
    tags: ["cieleta", "mlode-zwierzeta", "starter"],
  },
  {
    id: "prod-5",
    name: "Soymax Premium Plus 25kg",
    category: "premium",
    description: "Wzbogacona formuła Premium z dodatkami mineralnymi",
    protein: 47,
    weight: 25,
    unit: "kg",
    pricePerUnit: 280,
    imageUrl: "/premium-plus-enhanced-feed.jpg",
    inStock: true,
    features: [
      "Dodatki mineralne i witaminy",
      "Zawartość białka 47%",
      "Dla wysokowydajnych stad",
      "Wspomaga produkcję mleka",
    ],
    tags: ["bydlo-mleczne", "premium", "mineraly"],
  },
  {
    id: "prod-6",
    name: "Soymax Bio Standard 20kg",
    category: "bio",
    description: "Standardowa pasza ekologiczna w przystępnej cenie",
    protein: 43,
    weight: 20,
    unit: "kg",
    pricePerUnit: 280,
    imageUrl: "/bio-standard-organic-feed.jpg",
    inStock: false,
    features: ["Certyfikat ekologiczny", "Zawartość białka 43%", "Bez GMO", "Dobra cena w segmencie bio"],
    tags: ["bio", "ekologiczny", "budzet"],
  },
]

// Role systemowe
export const mockRoles: Role[] = [
  {
    id: "role-admin",
    name: "admin",
    displayName: "Administrator",
    description: "Pełny dostęp do wszystkich funkcji systemu. Zarządzanie użytkownikami, rolami i ustawieniami.",
    permissions: [
      "products.view", "products.edit", "products.delete",
      "distributors.view", "distributors.edit", "distributors.delete",
      "clients.view", "clients.edit", "clients.delete",
      "promotions.view", "promotions.edit", "promotions.delete",
      "sales.view",
      "settings.view", "settings.edit",
      "users.view", "users.edit", "users.delete",
      "roles.view", "roles.edit",
    ],
  },
  {
    id: "role-salesperson",
    name: "salesperson",
    displayName: "Handlowiec",
    description: "Zarządzanie przypisanymi dystrybutorami i ich klientami. Podgląd produktów i promocji.",
    permissions: [
      "products.view",
      "distributors.view_own", "distributors.edit",
      "clients.view_own", "clients.edit",
      "promotions.view",
      "sales.view_own",
    ],
  },
]

// Użytkownicy panelu administracyjnego
export const mockAdminUsers: AdminUser[] = [
  {
    id: "user-1",
    firstName: "Jan",
    lastName: "Administracyjny",
    email: "jan.admin@soymax.pl",
    phone: "+48 600 000 001",
    role: "admin",
    assignedDistributorIds: [],
    isActive: true,
    createdAt: "2024-01-01",
  },
  {
    id: "user-2",
    firstName: "Anna",
    lastName: "Kowalska",
    email: "anna.kowalska@soymax.pl",
    phone: "+48 600 123 456",
    role: "salesperson",
    assignedDistributorIds: ["dist-1", "dist-2", "dist-5", "dist-8"],
    isActive: true,
    createdAt: "2024-02-15",
  },
  {
    id: "user-3",
    firstName: "Marek",
    lastName: "Wiśniewski",
    email: "marek.wisniewski@soymax.pl",
    phone: "+48 601 234 567",
    role: "salesperson",
    assignedDistributorIds: ["dist-3", "dist-4"],
    isActive: true,
    createdAt: "2024-03-10",
  },
  {
    id: "user-4",
    firstName: "Katarzyna",
    lastName: "Nowak",
    email: "katarzyna.nowak@soymax.pl",
    phone: "+48 602 345 678",
    role: "salesperson",
    assignedDistributorIds: ["dist-6", "dist-7"],
    isActive: true,
    createdAt: "2024-04-20",
  },
  {
    id: "user-5",
    firstName: "Piotr",
    lastName: "Zieliński",
    email: "piotr.zielinski@soymax.pl",
    phone: "+48 603 456 789",
    role: "salesperson",
    assignedDistributorIds: [],
    isActive: false,
    createdAt: "2024-01-15",
  },
]

export const mockDistributorsList: Distributor[] = [
  {
    id: "dist-1",
    companyName: "AgroPartner Sp. z o.o.",
    nip: "1234567890",
    address: "ul. Polna 15, 00-001 Warszawa",
    phone: "+48 501 234 567",
    email: "kontakt@agropartner.pl",
    distributorCode: "DIST-2024-0042",
    baseDiscount: 5,
    programDiscount: 2,
    consultant: mockConsultant,
    registeredClientsCount: 18,
    activeClientsCount: 15,
  },
  {
    id: "dist-2",
    companyName: "Agro-Lider Sp. z o.o.",
    nip: "9876543210",
    address: "ul. Wiejska 42, 60-200 Poznań",
    phone: "+48 502 345 678",
    email: "biuro@agrolider.pl",
    distributorCode: "DIST-2024-0015",
    baseDiscount: 7,
    programDiscount: 3,
    consultant: mockConsultant,
    registeredClientsCount: 87,
    activeClientsCount: 72,
  },
  {
    id: "dist-3",
    companyName: "FarmPartner",
    nip: "5678901234",
    address: "ul. Rolnicza 8, 30-100 Kraków",
    phone: "+48 503 456 789",
    email: "info@farmpartner.pl",
    distributorCode: "DIST-2024-0023",
    baseDiscount: 6,
    programDiscount: 2,
    consultant: {
      id: "cons-2",
      firstName: "Marek",
      lastName: "Wiśniewski",
      phone: "+48 601 234 567",
      email: "marek.wisniewski@soymax.pl",
    },
    registeredClientsCount: 72,
    activeClientsCount: 58,
  },
  {
    id: "dist-4",
    companyName: "ZielonePole",
    nip: "3456789012",
    address: "ul. Łąkowa 22, 50-300 Wrocław",
    phone: "+48 504 567 890",
    email: "kontakt@zielonepole.pl",
    distributorCode: "DIST-2024-0031",
    baseDiscount: 5,
    programDiscount: 3,
    consultant: {
      id: "cons-2",
      firstName: "Marek",
      lastName: "Wiśniewski",
      phone: "+48 601 234 567",
      email: "marek.wisniewski@soymax.pl",
    },
    registeredClientsCount: 65,
    activeClientsCount: 51,
  },
  {
    id: "dist-5",
    companyName: "AgroBiznes24",
    nip: "2345678901",
    address: "ul. Przemysłowa 5, 80-400 Gdańsk",
    phone: "+48 505 678 901",
    email: "sklep@agrobiznes24.pl",
    distributorCode: "DIST-2024-0008",
    baseDiscount: 4,
    programDiscount: 1,
    consultant: mockConsultant,
    registeredClientsCount: 54,
    activeClientsCount: 42,
  },
  {
    id: "dist-6",
    companyName: "PolskaFarma",
    nip: "6789012345",
    address: "ul. Słoneczna 17, 20-500 Lublin",
    phone: "+48 506 789 012",
    email: "biuro@polskafarma.pl",
    distributorCode: "DIST-2024-0056",
    baseDiscount: 5,
    programDiscount: 2,
    consultant: {
      id: "cons-3",
      firstName: "Katarzyna",
      lastName: "Nowak",
      phone: "+48 602 345 678",
      email: "katarzyna.nowak@soymax.pl",
    },
    registeredClientsCount: 48,
    activeClientsCount: 39,
  },
  {
    id: "dist-7",
    companyName: "Rolnik Plus",
    nip: "4567890123",
    address: "ul. Ogrodowa 33, 40-600 Katowice",
    phone: "+48 507 890 123",
    email: "sklep@rolnikplus.pl",
    distributorCode: "DIST-2024-0072",
    baseDiscount: 3,
    programDiscount: 1,
    consultant: {
      id: "cons-3",
      firstName: "Katarzyna",
      lastName: "Nowak",
      phone: "+48 602 345 678",
      email: "katarzyna.nowak@soymax.pl",
    },
    registeredClientsCount: 32,
    activeClientsCount: 25,
  },
  {
    id: "dist-8",
    companyName: "Gospodarstwo Zdrowe",
    nip: "7890123456",
    address: "ul. Zielona 9, 70-700 Szczecin",
    phone: "+48 508 901 234",
    email: "kontakt@gospodarstwo-zdrowe.pl",
    distributorCode: "DIST-2024-0089",
    baseDiscount: 4,
    programDiscount: 2,
    consultant: mockConsultant,
    registeredClientsCount: 41,
    activeClientsCount: 35,
  },
]

// Wizyty handlowców u dystrybutorów
export const mockVisits: Visit[] = [
  {
    id: "visit-1",
    distributorId: "dist-1",
    salespersonId: "user-2",
    date: "2026-01-15",
    note: "Omówienie nowej oferty produktowej na Q1. Klient zainteresowany paszą Premium Plus.",
    createdAt: "2026-01-15T10:30:00",
  },
  {
    id: "visit-2",
    distributorId: "dist-1",
    salespersonId: "user-2",
    date: "2025-12-20",
    note: "Podsumowanie roku 2025. Ustalenie celów sprzedażowych na 2026.",
    createdAt: "2025-12-20T14:00:00",
  },
  {
    id: "visit-3",
    distributorId: "dist-2",
    salespersonId: "user-2",
    date: "2026-01-10",
    note: "Prezentacja nowej promocji zimowej. Klient zamówił dodatkową partię paszy Bio.",
    createdAt: "2026-01-10T09:15:00",
  },
  {
    id: "visit-4",
    distributorId: "dist-3",
    salespersonId: "user-3",
    date: "2026-01-12",
    note: "Rozwiązanie reklamacji z poprzedniego miesiąca. Klient zadowolony z szybkiej reakcji.",
    createdAt: "2026-01-12T11:00:00",
  },
  {
    id: "visit-5",
    distributorId: "dist-3",
    salespersonId: "user-3",
    date: "2025-11-28",
    note: "Szkolenie z nowego systemu zamówień online.",
    createdAt: "2025-11-28T13:30:00",
  },
  {
    id: "visit-6",
    distributorId: "dist-4",
    salespersonId: "user-3",
    date: "2026-01-08",
    note: "Wizyta kontrolna. Sprawdzenie stanów magazynowych i omówienie potrzeb na luty.",
    createdAt: "2026-01-08T10:00:00",
  },
  {
    id: "visit-7",
    distributorId: "dist-6",
    salespersonId: "user-4",
    date: "2026-01-14",
    note: "Negocjacje warunków współpracy na 2026. Ustalono nowy próg rabatowy.",
    createdAt: "2026-01-14T15:00:00",
  },
  {
    id: "visit-8",
    distributorId: "dist-7",
    salespersonId: "user-4",
    date: "2026-01-05",
    note: "Pierwsza wizyta po świętach. Klient planuje zwiększenie zamówień o 20%.",
    createdAt: "2026-01-05T09:30:00",
  },
]

// Nagrody do wymiany za punkty
export const mockRewards: Reward[] = [
  {
    id: "reward-1",
    name: "Czapka SOYMAX",
    description: "Stylowa czapka z logo SOYMAX. Idealna na pole i do codziennego użytku.",
    pointsCost: 500,
    imageUrl: "/reward-cap.jpg",
    category: "gadget",
    pickupType: "distributor",
    inStock: true,
  },
  {
    id: "reward-2",
    name: "Kurtka robocza SOYMAX",
    description: "Wytrzymała kurtka robocza z oddychającego materiału. Rozmiary S-XXL.",
    pointsCost: 2500,
    imageUrl: "/reward-jacket.jpg",
    category: "gadget",
    pickupType: "soymax",
    inStock: true,
  },
  {
    id: "reward-3",
    name: "Voucher 100 PLN",
    description: "Voucher na zakupy produktów SOYMAX o wartości 100 PLN.",
    pointsCost: 1000,
    imageUrl: "/reward-voucher-100.jpg",
    category: "voucher",
    pickupType: "distributor",
    inStock: true,
  },
  {
    id: "reward-4",
    name: "Voucher 250 PLN",
    description: "Voucher na zakupy produktów SOYMAX o wartości 250 PLN.",
    pointsCost: 2000,
    imageUrl: "/reward-voucher-250.jpg",
    category: "voucher",
    pickupType: "distributor",
    inStock: true,
  },
  {
    id: "reward-5",
    name: "Próbka paszy Premium 5kg",
    description: "Darmowa próbka paszy SOYMAX Premium 5kg do przetestowania.",
    pointsCost: 300,
    imageUrl: "/reward-sample.jpg",
    category: "product",
    pickupType: "distributor",
    inStock: true,
  },
  {
    id: "reward-6",
    name: "Termos SOYMAX 1L",
    description: "Wysokiej jakości termos stalowy z logo SOYMAX. Utrzymuje temperaturę do 12h.",
    pointsCost: 800,
    imageUrl: "/reward-thermos.jpg",
    category: "gadget",
    pickupType: "distributor",
    inStock: true,
  },
  {
    id: "reward-7",
    name: "Szkolenie online",
    description: "Dostęp do profesjonalnego szkolenia online z zakresu żywienia zwierząt.",
    pointsCost: 1500,
    imageUrl: "/reward-training.jpg",
    category: "experience",
    pickupType: "soymax",
    inStock: true,
  },
  {
    id: "reward-8",
    name: "Zestaw narzędzi ogrodowych",
    description: "Profesjonalny zestaw narzędzi ogrodowych w walizce SOYMAX.",
    pointsCost: 3500,
    imageUrl: "/reward-tools.jpg",
    category: "gadget",
    pickupType: "soymax",
    inStock: false,
  },
]

// Przykładowe wymienione nagrody klienta
export const mockRedemptions: Redemption[] = [
  {
    id: "redemption-1",
    clientId: "client-1",
    rewardId: "reward-1",
    rewardName: "Czapka SOYMAX",
    pointsSpent: 500,
    status: "collected",
    redeemedAt: "2025-11-15T10:30:00",
    pickupType: "distributor",
  },
  {
    id: "redemption-2",
    clientId: "client-1",
    rewardId: "reward-3",
    rewardName: "Voucher 100 PLN",
    pointsSpent: 1000,
    status: "ready",
    redeemedAt: "2026-01-10T14:00:00",
    pickupType: "distributor",
  },
]

// Dane klienta końcowego (dla widoku konta klienta)
export const mockEndCustomer = {
  id: "client-1",
  firstName: "Jan",
  lastName: "Nowak",
  phone: "+48 600 111 222",
  email: "jan.nowak@gmail.com",
  points: 1250,
  customerCode: "CUST-2024-00142",
}

// Programy lojalnosciowe
export const mockLoyaltyPrograms: LoyaltyProgram[] = [
  {
    id: "prog-1",
    name: "Program Podstawowy",
    description: "Standardowy program punktowy. Za kazdy zakup passzy naliczane sa punkty wedlug przelicznika.",
    operations: ["Zakup produktow", "Rejestracja nowego klienta"],
    multiplier: 1,
    isActive: true,
    startDate: "2024-01-01",
    endDate: "2026-12-31",
  },
  {
    id: "prog-2",
    name: "Program Premium",
    description: "Program premiowy dla dystrybutorów z obrotem powyzej 50 000 PLN/rok. Podwojny przelicznik punktow.",
    operations: ["Zakup produktow", "Rejestracja nowego klienta", "Polecenie dystrybutora"],
    multiplier: 2,
    isActive: true,
    startDate: "2025-01-01",
    endDate: "2026-12-31",
  },
  {
    id: "prog-3",
    name: "Program Sezonowy Zima 2026",
    description: "Dodatkowe punkty za zakup paszy Premium i Bio w sezonie zimowym.",
    operations: ["Zakup produktow Premium", "Zakup produktow Bio"],
    multiplier: 3,
    isActive: false,
    startDate: "2025-12-01",
    endDate: "2026-02-28",
  },
]

// Historia punktow dystrybutora
export const mockPointsHistory: PointsHistoryEntry[] = [
  { id: "ph-1", date: "2026-02-10", operation: "Zakup: Soymax Premium 25kg x4", points: 40, balance: 250 },
  { id: "ph-2", date: "2026-02-05", operation: "Wymiana: Voucher 50 PLN", points: -100, balance: 210 },
  { id: "ph-3", date: "2026-01-28", operation: "Zakup: Soymax Bio+ 20kg x2", points: 30, balance: 310 },
  { id: "ph-4", date: "2026-01-20", operation: "Rejestracja klienta: Agnieszka Zielinska", points: 50, balance: 280 },
  { id: "ph-5", date: "2026-01-15", operation: "Zakup: Soymax Standard 25kg x6", points: 48, balance: 230 },
  { id: "ph-6", date: "2026-01-10", operation: "Bonus: Program Sezonowy Zima", points: 100, balance: 182 },
  { id: "ph-7", date: "2025-12-28", operation: "Zakup: Soymax Starter 10kg x3", points: 21, balance: 82 },
  { id: "ph-8", date: "2025-12-20", operation: "Zakup: Soymax Premium Plus 25kg x2", points: 22, balance: 61 },
  { id: "ph-9", date: "2025-12-15", operation: "Rejestracja klienta: Tomasz Lewandowski", points: 50, balance: 39 },
  { id: "ph-10", date: "2025-12-01", operation: "Bonus powitalny", points: -11, balance: -11 },
]

// Wymiany nagrod (widok admina)
export const mockAdminRedemptions: AdminRedemption[] = [
  {
    id: "ar-1",
    clientId: "client-1",
    rewardId: "reward-1",
    rewardName: "Czapka SOYMAX",
    pointsSpent: 500,
    status: "collected",
    redeemedAt: "2025-11-15T10:30:00",
    pickupType: "distributor",
    clientName: "Jan Nowak",
    clientEmail: "jan.nowak@gmail.com",
  },
  {
    id: "ar-2",
    clientId: "client-4",
    rewardId: "reward-2",
    rewardName: "Kurtka robocza SOYMAX",
    pointsSpent: 2000,
    status: "ready",
    redeemedAt: "2026-01-20T14:00:00",
    pickupType: "soymax",
    clientName: "Agnieszka Zielinska",
    clientEmail: "a.zielinska@onet.pl",
  },
  {
    id: "ar-3",
    clientId: "client-2",
    rewardId: "reward-3",
    rewardName: "Voucher 100 PLN",
    pointsSpent: 1000,
    status: "pending",
    redeemedAt: "2026-02-01T09:15:00",
    pickupType: "distributor",
    clientName: "Maria Wisniewska",
    clientEmail: "maria.w@gmail.com",
  },
  {
    id: "ar-4",
    clientId: "client-5",
    rewardId: "reward-4",
    rewardName: "Termos turystyczny",
    pointsSpent: 750,
    status: "pending",
    redeemedAt: "2026-02-08T16:30:00",
    pickupType: "delivery",
    clientName: "Tomasz Lewandowski",
    clientEmail: "t.lewandowski@gmail.com",
  },
  {
    id: "ar-5",
    clientId: "client-1",
    rewardId: "reward-3",
    rewardName: "Voucher 100 PLN",
    pointsSpent: 1000,
    status: "collected",
    redeemedAt: "2025-10-05T11:00:00",
    pickupType: "distributor",
    clientName: "Jan Nowak",
    clientEmail: "jan.nowak@gmail.com",
  },
]

// Rabaty dystrybutora
export const mockDiscounts: Discount[] = [
  {
    id: "disc-1",
    name: "Rabat 10%",
    code: "SOYMAX10",
    description: "10% rabatu na wszystkie zamówienia",
    type: "percentage",
    value: 10,
    expiryDate: "2026-06-30",
    active: true,
  },
  {
    id: "disc-2",
    name: "500 zł zniżki",
    code: "SOYMAX500",
    description: "Dodatkowe 500 zł na zamówienia powyżej 5000 zł",
    type: "fixed",
    value: 500,
    minOrderValue: 5000,
    expiryDate: "2026-04-30",
    active: true,
  },
  {
    id: "disc-3",
    name: "Rabat 15%",
    code: "PREMIUM15",
    description: "15% rabatu dla klientów premium",
    type: "percentage",
    value: 15,
    expiryDate: "2026-07-31",
    active: true,
  },
  {
    id: "disc-4",
    name: "250 zł zniżki",
    code: "SPRING250",
    description: "Wiosenna promocja - 250 zł zniżki",
    type: "fixed",
    value: 250,
    minOrderValue: 2000,
    expiryDate: "2026-03-31",
    active: true,
  },
  {
    id: "disc-5",
    name: "Rabat 5%",
    code: "LOYAL5",
    description: "Rabat lojalności 5% na każde zamówienie",
    type: "percentage",
    value: 5,
    expiryDate: "2026-12-31",
    active: true,
  },
]
